"""
Using a simple model for now cause I did not want to purchase
any inference providers/credits for now
"""
from fastapi import HTTPException
from app.core.config import get_settings
import httpx
from app.db.supabase_db import get_user_id, get_user_styles
from fastapi.responses import Response

settings = get_settings()
HEADERS = {"Authorization": f"Bearer {settings.cloudflare_api_key}"}
API_URL = f"https://api.cloudflare.com/client/v4/accounts/{settings.cloudflare_account_id}/ai/run/@cf/runwayml/stable-diffusion-v1-5-inpainting"

async def generate_image_inpainting(mask_input, image_input, revised_prompt, token):
    print("Generating image with inpainting...")
    user_id =  get_user_id(token)
    user_style =  await get_user_styles(user_id)
    user_style, user_genre, user_artist = user_style[0]['style'], user_style[0]['genre'], user_style[0]['artist']
    revised_prompt = f"{revised_prompt}Ensure the image follows {user_style} art style, {user_genre} genre, and {user_artist} artist style."
    #prompt is generated by the reinforcement learning agent
    image_bytes = await image_input.read()
    mask_bytes = await mask_input.read()
    image_array = list(image_bytes)
    mask_array = list(mask_bytes)
    inputs = {
        "prompt": revised_prompt,
        "image": image_array,
        "mask": mask_array,
    }   

    async with httpx.AsyncClient() as client:
        response = await client.post(API_URL, headers=HEADERS, json=inputs)
        if response.status_code == 200:
            image_bytes = response.content
            return Response(content = image_bytes, media_type="image/jpeg")
        else:
            raise HTTPException(
                status_code=response.status_code,
                detail=f"Failed to generate image: {response.text}",
            )
        